# Generated by Django 4.1.7 on 2023-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.CharField(choices=[('Very Important', 'the content of the post is very important'), ('Even Important', 'the content of the post it is moderately important'), ('Not Impotant', 'casual post, low importance')], default='Even Important', max_length=100),
        ),
    ]
