# Generated by Django 4.1.7 on 2023-02-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='importance',
            field=models.CharField(choices=[('Very Important', 'Content very important'), ('Even Important', 'Content moderately important'), ('Not Impotant', 'Casual post, low importance')], default='Even Important', max_length=100),
        ),
    ]
